# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 265a000323ca232c1c82692aba464e14bf53d74449402a3cb4af88f2cb0a416452949b994861f1873afcd7d232ed686ccd715f9af1c256bc0ce500565809b801

test:
  secret_key_base: 1bc5a45b653bed6ae745945de73837b63c506304223e95a7dbeca2fd8607d1739c2b45cc13f2035d478cedfae74b30240362920ebbba5c280f6f761d92d0e6b5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
